files:
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\LV32MX
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: 199A10BF39EFE8C67E8A1C840D37B215
  logicalPath: config\LV32MX
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D44CE45FBC362D0A34A5CAC6B03D48D3
- generatedChecksum: 6472C6C26D24667C789468C50FA33346
  logicalPath: config\LV32MX
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6472C6C26D24667C789468C50FA33346
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5C73B66633AD0871EE9740FAD5CE05AB
  logicalPath: config\LV32MX\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5C73B66633AD0871EE9740FAD5CE05AB
- generatedChecksum: 19DDA090C007DC96A1DBD07984E7394C
  logicalPath: config\LV32MX\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 19DDA090C007DC96A1DBD07984E7394C
- generatedChecksum: 08BBEADF532AC563F18C1E6D8050D440
  logicalPath: config\LV32MX\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 08BBEADF532AC563F18C1E6D8050D440
- generatedChecksum: 1242C5E836184C3CB6A10786BAA366A5
  logicalPath: config\LV32MX\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1242C5E836184C3CB6A10786BAA366A5
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\LV32MX\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 0A2CB7652AEB6CFA321837326A048B78
  logicalPath: config\LV32MX
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A2CB7652AEB6CFA321837326A048B78
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\LV32MX
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\LV32MX\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 81B2AF10CCF29049B2D41F7FB63DFD19
  logicalPath: config\LV32MX\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 81B2AF10CCF29049B2D41F7FB63DFD19
- generatedChecksum: 91B78584EA427C0B724BA5DBD34F7257
  logicalPath: config\LV32MX\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 91B78584EA427C0B724BA5DBD34F7257
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config\LV32MX\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\LV32MX\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\LV32MX
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 10EDE1BE00DC5CDD6C4820DE6C35D806
  logicalPath: config\LV32MX
  name: p32MZ0512EFE064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 10EDE1BE00DC5CDD6C4820DE6C35D806
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/LV32MX;../src/packs/PIC32MZ0512EFE064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/LV32MX;../src/packs/PIC32MZ0512EFE064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
