configName: CuriosityBoard
folderName: ''
format_version: v1.0
frameworkPath: ../../HarmonyFramework
processor: PIC32MZ2048EFM100
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;core_apps_pic32mx;core_apps_pic32mz_ef;crypto;csp;csp_apps_pic32mx;csp_apps_pic32mz_ef;dev_packs;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;net;quick_docs;touch;touch_apps;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM100.atdf
